### ISSUE TITLE
Landing Page Sameer Requests

### ISSUE THREAD

**Issue by RobinJayaswal** [DartPoll/app#47]
Die dot font. 

Text sizes should match 

Log in smaller and capitalized

Scroll down in bottom middle.

Go based on mockup for text positioning.

Mobile compatibility

Phone should be a video of app being used

**Comment by ben-pr-p** [comment]
1df8abd04a42df0bce1b0d73952b9bc3287bd780

Mobile compatibility requires full redesign

What does phone should be a video of app being used mean?
